### ISSUE TITLE
Spaces or a dash follow by digits in the CallerID field in DVSwitch causes table issues in Allmon3 home page

### ISSUE THREAD

**Issue by knobby4444** [AllStarLink/Allmon3#253]
**Describe the bug**
This applies to DVSwitch connections, but likely affects other clients as well.  When setting up the node in DVSwitch, the CallerID field is free form.  This field populates the Node column in the Allmon3 UI when joining the node as a phone.  Typically the callsign is entered here.  If one appends a "-1" or dash followed by any digits at the end, it causes the column data to move around in the Allmon3 table columns, and the ip address of the phone is added to the end of the node field.  Also if one puts a space in the CallerID field in DVSwitch, the table in Allmon3 disappears.

**To Reproduce**
1. Setup node and give the iaxclient stanza in iax.conf a password
2. Setup DVSwitch on a phone and create a connection to the node using the iaxclient settings, putting data in the CallerID field with a dash followed by digits at the end like "KG5DRT-1" or "ASL-234234".  Alternatively, put anything in the CallerID field that includes a space like "KG5DRT 1"
3. Join the node with DVSwitch
4. See issues in Allmon3 UI, fields swapped around with dash and digit, table gone with space

**Expected behavior**
Joining the node with any text in the CallerID field allowed in DVSwitch or other apps will not cause issues with the table data in Allmon3

**Screenshots**
Good table:
![image](https://github.com/user-attachments/assets/6ff11c42-80c6-42b7-8f28-1271ee56cae9)

With dash:
![image](https://github.com/user-attachments/assets/f41731fb-3300-4735-b032-5aee046763a5)

With space:
![image](https://github.com/user-attachments/assets/a4529e58-695d-4ee1-89fc-1d3bcbcb2211)

**URL of Site**
This affects all Allmon3 instances I have tried

**Log Information**
Here is the connect with a space in CALLING NAME, or the CallerID field in DVSwitch
allstar-3*CLI> iax2 set debug on
IAX2 Debugging Enabled
Rx-Frame Retry[ No] -- OSeqno: 000 ISeqno: 000 Type: IAX     Subclass: NEW    
    Timestamp: 00001ms  SCall: 15119  DCall: 00000 192.168.10.61:4570
    CALLTOKEN       : Present

Tx-Frame Retry[ No] -- OSeqno: 000 ISeqno: 001 Type: IAX     Subclass: CTOKEN 
    Timestamp: 00001ms  SCall: 00001  DCall: 15119 192.168.10.61:4570
    CALLTOKEN       : 51 bytes

Rx-Frame Retry[ No] -- OSeqno: 001 ISeqno: 001 Type: IAX     Subclass: ACK    
    Timestamp: 00001ms  SCall: 15119  DCall: 00001 192.168.10.61:4570
Rx-Frame Retry[ No] -- OSeqno: 000 ISeqno: 000 Type: IAX     Subclass: NEW    
    Timestamp: 00000ms  SCall: 15120  DCall: 00000 192.168.10.61:4570
    VERSION         : 2
    CALLED NUMBER   : 49520
    CALLING NUMBER  : 
    CALLING NAME    : KG5DRT 1
    USERNAME        : jake-dvswitch
    FORMAT          : 108
    CODEC_PREFS     : (slin|ulaw|adpcm|alaw)
    CALLTOKEN       : 51 bytes

Tx-Frame Retry[-01] -- OSeqno: 000 ISeqno: 001 Type: IAX     Subclass: ACK    
    Timestamp: 00004ms  SCall: 00882  DCall: 15120 192.168.10.61:4570
Tx-Frame Retry[000] -- OSeqno: 000 ISeqno: 001 Type: IAX     Subclass: AUTHREQ
    Timestamp: 00007ms  SCall: 00882  DCall: 15120 192.168.10.61:4570
    AUTHMETHODS     : 2
    CHALLENGE       : \x34\x38\x32\x39\x36\x33\x32\x36\x36
    USERNAME        : jake-dvswitch

Rx-Frame Retry[ No] -- OSeqno: 001 ISeqno: 001 Type: IAX     Subclass: AUTHREP
    Timestamp: 00013ms  SCall: 15120  DCall: 00882 192.168.10.61:4570
    USERNAME        : jake-dvswitch
    MD5 RESULT      : 70b37ce1bc1f0fc0de71f0e768d8d902
    REFRESH         : 60

Tx-Frame Retry[-01] -- OSeqno: 001 ISeqno: 002 Type: IAX     Subclass: ACK    
    Timestamp: 00013ms  SCall: 00882  DCall: 15120 192.168.10.61:4570
Tx-Frame Retry[000] -- OSeqno: 001 ISeqno: 002 Type: IAX     Subclass: ACCEPT 
    Timestamp: 00017ms  SCall: 00882  DCall: 15120 192.168.10.61:4570
    FORMAT          : 4

**Version Info**
root@allstar-3:~# asl-show-version 
********** AllStarLink [ASL] Version Info **********

OS            : Debian GNU/Linux 12 (bookworm)
OS Kernel     : 6.6.51+rpt-rpi-v8

Asterisk      : 20.9.3+asl3-3.0.6-1.deb12
ASL [app_rpt] : 3.0.6

Installed ASL packages :

  Package                         Version
  ==============================  ==============================
  allmon3                         1.3.4-1.deb12
  asl3                            3.5.0-1.deb
  asl3-asterisk                   2:20.9.3+asl3-3.0.6-1.deb12
  asl3-asterisk-config            2:20.9.3+asl3-3.0.6-1.deb12
  asl3-asterisk-modules           2:20.9.3+asl3-3.0.6-1.deb12
  asl3-menu                       1.9-1.deb12
  asl3-update-nodelist            1.5.1-1.deb12
  dahdi                           1:3.1.0-2
  dahdi-dkms                      1:3.4.0-4+asl
  dahdi-linux                     1:3.4.0-4+asl

**Additional context**
Behavior is the same with text i n the CALLING NAME field, named Caller Number in DVSwitch.  Adding a dash digit or space to the Caller Number does not cause any issues.

**Comment by jxmx** [comment]
https://github.com/AllStarLink/Allmon3/issues/254

**Comment by jxmx** [comment]
@knobby4444 - Will you please try copying https://github.com/AllStarLink/Allmon3/blob/xstat_rewrite/src/asl_allmon/ami_parser/__init__.py to `/usr/lib/python3/dist-packages/asl_allmon/ami_parser/__init__.py`. See if this resolves the issue.

**Comment by jxmx** [comment]
I believe this is fixed by pull #256 and will shortly appear in the 1.4 beta.

**Comment by knobby4444** [comment]
Was away yesterday and the link above is dead after merge.  Will test once beta rolls around.

**Comment by jxmx** [comment]
It’s out. Just not announced.

On Oct 22, 2024, at 7:01 AM, Jake ***@***.***> wrote:

﻿

Was away yesterday and the link above is dead after merge. Will test once beta rolls around.

**Comment by knobby4444** [comment]
The dash digit issue appears fixed:
![image](https://github.com/user-attachments/assets/8400446b-81ac-4d01-ac69-3e1805e5e46f)
The space issue still makes the table disappear, in screen shot below, I used "KG5DRT ONE" for callerid in DVSwitch:
![image](https://github.com/user-attachments/assets/d27a8b63-73f6-4858-b84b-cec4a35e508a)

**Comment by knobby4444** [comment]
I did just notice that when using a dash digit at the end, it did still append the IP address of the DVSwitch phone to the end of the node name and I don't think that is expected.

**Comment by knobby4444** [comment]
Interesting issue now.  Last night the 2M net was on and we had people linked in via allstar and echo.  I tried loading the allmon home and the table was missing again.  I figured I must me logged in with dvswitch in a bad way so I went to check and I was not.  I had my call with no dash or spaces.  But still the table was missing.  I looked at the node map to see if someone else had something and no one did.  One person on echo had a -R at the end of their call but that has never been a problem.  Here is what the node map looked like at that time:
![Screenshot at 2024-10-23 20-15-32](https://github.com/user-attachments/assets/4a3fb2dd-4563-44f3-89e6-f9673a324e35)

I tried restarting allmon a few times and I closed my browser, etc.  Nothing would get it going.  Net was on so I did not try to reboot.  Then after a few minutes, it just loaded and I don't know why.  Here is what it looked like, with additional info on echo nodes, very nice:
![Screenshot at 2024-10-23 20-27-35](https://github.com/user-attachments/assets/06c3c6c1-ec1b-4fcd-80a6-e503b369bd8c)

It was working fine this morning for an hour or so, and then it just did it again, table has disappeared.  Checking the system logs and I find this, many times each second:
Oct 24 06:52:13 allstar-3 allmon3[193413]: ERROR: (asl_allmon.allmon3_ws_status) ERROR: list index out of range
There is one echo node connected this morning.  It was connected when allmon was working, and it is still the only node connected now that allmon is missing the table.

**Comment by knobby4444** [comment]
At 9:21 the final error message was in syslog.  The table is back and allmon is working.  Only thing that might be interesting in /var/log/asterisk/messages is this:

[2024-10-24 09:23:00.749] WARNING[176281] chan_echolink.c: Countdown for Callsign W5NPR, IP Address 44.137.75.249 is negative.

Not sure when NPR joined the node, I wasn't looking at the network map at the time.

**Comment by jxmx** [comment]
It would  be really helpful if, when oit's happening, you stop the allmon3 service and run allmon3 by hand from the shell as `allmon3 --debug`, refresh the browser window, and then capture about 10 seconds of output. It's A LOT of output.

**Comment by picchiosat** [comment]
allmon3 ver 1.4.0

DEBUG: (asl_allmon.ami_parser) enter get_echolink_name(3066366)
DEBUG: (asl_allmon.ami_conn) enter asl_cmd_response()
DEBUG: (asl_allmon.ami_conn) command >> ACTION: COMMAND COMMAND: echolink dbget nodename **066366**  ActionID: 86020c1a-277b-41d1-8636-ef3d5198a34a
DEBUG: (asl_allmon.ami_conn) response >> Response: Error  Message: Command output follows  Output: Error: Entry for 066366 not found!  Output: Command 'echolink dbget nodename 066366' failed.
DEBUG: (asl_allmon.ami_parser) exiting get_echolink_name(3066366)
ERROR: (asl_allmon.allmon3_ws_status) ERROR: list index out of range
DEBUG: (asl_allmon.allmon3_ws_status) Node 50737 - status_connections: 1
DEBUG: (asl_allmon.allmon3_ws_status) broadcasting 50737
DEBUG: (asl_allmon.ami_parser) entering parse_xstat(50737)
DEBUG: (asl_allmon.ami_conn) enter asl_cmd_response()
DEBUG: (asl_allmon.ami_conn) command >> ACTION: RptStatus COMMAND: XStat NODE: 50737  ActionID: d0a3730f-cc83-4643-800b-6f4afd9c02e3

the echolink node has ID 66366 not 066366

**Comment by knobby4444** [comment]
Okay, appears to be happening when an echolink station connects, but not a dvswitch connection.  And this morning for some time, it worked when there was an echo connection.
[allmon-debug.txt](https://github.com/user-attachments/files/17513091/allmon-debug.txt)

**Comment by jxmx** [comment]
Interesting. Echolink connected nodes w/o DB entries. That's something I didn't account for. I'll try to whip out a fix tonight or tomorrow.

**Comment by jxmx** [comment]
Try copying this file to `/usr/lib/python3/dist-packages/asl_allmon/ami_parser`:

https://raw.githubusercontent.com/AllStarLink/Allmon3/refs/heads/253_t2/src/asl_allmon/ami_parser/__init__.py

**Comment by picchiosat** [comment]
after patch:

DEBUG: (asl_allmon.ami_parser) enter get_echolink_name(3066366)
DEBUG: (asl_allmon.ami_conn) enter asl_cmd_response()
DEBUG: (asl_allmon.ami_conn) command >> ACTION: COMMAND COMMAND: echolink dbget nodename 066366  ActionID: 16b48422-2c90-47e7-99ad-206ba3bce4b4
DEBUG: (asl_allmon.ami_conn) response >> Response: Error  Message: Command output follows  Output: Error: Entry for 066366 not found!  Output: Command 'echolink dbget nodename 066366' failed.
**ERROR: (asl_allmon.allmon3_ws_status) ERROR: match() missing 1 required positional argument: 'string'**
DEBUG: (asl_allmon.allmon3_ws_status) Node 50737 - status_connections: 1
DEBUG: (asl_allmon.allmon3_ws_status) broadcasting 50737
DEBUG: (asl_allmon.ami_parser) entering parse_xstat(50737)
DEBUG: (asl_allmon.ami_conn) enter asl_cmd_response()
DEBUG: (asl_allmon.ami_conn) command >> ACTION: RptStatus COMMAND: XStat NODE: 50737  ActionID: cdbc359d-68f8-488a-ab1f-f75775a948a4

**Comment by knobby4444** [comment]
Same result.  Once I join the node via echo, the allmon homepage does nothing, then I click the Home link and the table disappears.  As soon as I disconnect, the table appears again immediately.  I can post another debug output each time if you want.

**Comment by jxmx** [comment]
> Error: Entry for 066366 not found! Output: Command 'echolink dbget nodename 066366' failed.

@picchiosat - is your Echolink node # really 066366?

**Comment by jxmx** [comment]
Maybe we can setup some time for people with this problem to connect to my test node 2116 so I can see what's going on in realtime.

**Comment by picchiosat** [comment]
> > Error: Entry for 066366 not found! Output: Command 'echolink dbget nodename 066366' failed.
> 
> 
> 
> @picchiosat - is your Echolink node # really 066366?

yes... node ID **66366** NOT **066366**

**Comment by jxmx** [comment]
Okay, so at least one problem is that AMI is added a leading zero to the node # that'll have to get stripped off. So that's another layered problem on top of the other one.

**Comment by jxmx** [comment]
@knobby4444 can you try copying the file at that link again over? I made another change and fixed a mistake.

**Comment by jxmx** [comment]
Also @picchiosat

**Comment by picchiosat** [comment]
Yep...
yes... it works!!
well done, congratulations

**Comment by jxmx** [comment]
@knobby4444 - Can you confirm this resolves the problem for you as well?

**Comment by knobby4444** [comment]
Seems to have fixed the dash digit problem.  Space still causes table to disappear, but hopefully not many people will be putting a space in a field for callsign.  I do notice now that when I disconnect and reconnect via echo, it shows a random node number and description in the table.  WA4OHV is not really in my node right now, that's me but wrong node number and description.  It was someone else earlier.
![image](https://github.com/user-attachments/assets/6952f774-02cb-4c57-b117-4bdd49cdf572)
